"addi t0,%[arr_size],0\n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"
"fsgnj.d f0,%[result],%[result]\n\t"
"addi %[others_cnt],%[others_cnt],1\n\t"
"Loop_float:\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"beq t0, x0, End_float\n\t"
"fld f1, 0(%[h])\n\t"
"addi %[dlw_cnt], %[dlw_cnt], 1\n\t"
"fld f2, 0(%[x])\n\t"
"addi %[dlw_cnt], %[dlw_cnt], 1\n\t"
"fmul.d f3, f1, f2\n\t"
"addi %[dmul_cnt], %[dmul_cnt], 1\n\t"
"fmul.d f0, f3, f0\n\t"
"addi %[dmul_cnt], %[dmul_cnt], 1\n\t"
"addi %[h], %[h], 8\n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"
"addi %[x], %[x], 8\n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"
"addi t0, t0, -1\n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"jal x0,Loop_float\n\t"
"End_float:\n\t"
"fsgnj.d %[result], f0,f0\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"

