"addi t0,%[arr_size],0\n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"
"fsgnj.s f0,%[result],%[result]\n\t"
"addi %[others_cnt],%[others_cnt],1\n\t"
"Loop_float:\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"beq t0, x0, End_float\n\t"
"flw f1, 0(%[h])\n\t"
"addi %[flw_cnt], %[flw_cnt], 1\n\t"
"flw f2, 0(%[x])\n\t"
"addi %[flw_cnt], %[flw_cnt], 1\n\t"
"fmul.s f3, f1, f2\n\t"
"addi %[fmul_cnt], %[fmul_cnt], 1\n\t"
"fmul.s f0, f3, f0\n\t"
"addi %[fmul_cnt], %[fmul_cnt], 1\n\t"
"addi %[h], %[h], 4\n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"
"addi %[x], %[x], 4\n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"
"addi t0, t0, -1\n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"jal x0,Loop_float\n\t"
"End_float:\n\t"
"fsgnj.s %[result],f0,f0\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"

