"add t0, %[m], x0\n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"
"addi t1, x0, 0\n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"
"Loop_bit:\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"beq t0, x0, End_bit\n\t"
"andi t2, %[b], 1\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"slli t1, t1, 1\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"or t1, t1, t2\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"srli %[b], %[b], 1\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"addi t0, t0, -1\n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"jal x0, Loop_bit\n\t"
"End_bit:\n\t"
"add %[b], t1, x0\n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"