"add t0, %[N], x0\n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"
"addi t1, x0, -1\n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"
"Loop_log:\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"beq t0, x0, End_log\n\t"
"srli t0, t0, 1\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"addi t1, t1, 1\n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"jal x0, Loop_log\n\t"
"End_log:\n\t"
"add %[log], t1, x0\n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"