"add t1, %[N], x0\n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"
"addi t2, x0, 1\n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"
"addi t3, x0, 1\n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"
"Loop_pi:\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"beq t1, x0, End_pi\n\t"
"fcvt.s.w f1, t2\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"fcvt.s.w f2, t3\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"fdiv.s f1, f1, f2\n\t"
"addi %[fdiv_cnt], %[fdiv_cnt], 1\n\t"
"fadd.s %[pi], %[pi], f1\n\t"
"addi %[fadd_cnt], %[fadd_cnt], 1\n\t"
"sub t2,x0,t2\n\t"
"addi %[sub_cnt], %[sub_cnt], 1\n\t"
"addi t3, t3, 2\n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"
"addi t1, t1, -1\n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"jal x0, Loop_pi\n\t"
"End_pi:\n\t"